[[linter]]
code = 'BLACK-ISORT'
include_patterns = [
    '*.py',
    '**/*.py',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'black_isort_linter',
    '--fast',
    '--',
    '@{{PATHSFILE}}',
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'black==24.10.0', # Use 24.x when ruff styles are updated
    'isort==5.13.2',
]
is_formatter = true

[[linter]]
code = 'RUSTFMT'
include_patterns = [
    '**/*.rs',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'rustfmt_linter',
    '--binary=rustfmt',
    '--config-path=.rustfmt.toml',
    '--',
    '@{{PATHSFILE}}',
]

[[linter]]
code = 'PYRE'
include_patterns = [
    '*.py',
    '**/*.py',
    '**/*.pyi',
]
command = [
    'python3',
    'tools/linter/adapters/pyre_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'pyre-check==0.9.23',
    'click==8.1.0',
]
is_formatter = false
