[[linter]]
code = 'CLANGFORMAT'
include_patterns = [
    '**/*.proto',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'clangformat_linter',
    '--binary=clang-format',
    '--fallback',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'clang-format==18.1.3',
]

[[linter]]
code = 'UFMT'
include_patterns = [
    '*.py',
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'ufmt_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'black==24.4.2',
    'ufmt==2.6.0',
    'usort==1.0.5',
]

[[linter]]
code = 'FLAKE'
include_patterns = [
    '*.py',
    '**/*.py',
]
exclude_patterns = []
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'flake8_linter',
    '--config=.flake8',
    '--',
    '@{{PATHSFILE}}',
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'flake8==7.3.0',
    'flake8-bugbear==24.12.12',
    'flake8-comprehensions==3.16.0',
    'flake8-executable==2.1.3',
    'flake8-logging-format==2024.24.12',
    'flake8-pyi==25.5.0',
    'flake8-simplify==0.22.0',
    'mccabe==0.7.0',
    'pycodestyle==2.14.0',
    'pyflakes==3.4.0',
    'torchfix==0.4.0 ; python_version >= "3.10" and python_version < "3.13"',
]
is_formatter = true

[[linter]]
code = 'RUSTFMT'
include_patterns = [
    '**/*.rs',
]
command = [
    'python',
    'tools/linter/adapters/rust_linter.py',
    '--binary=rustfmt',
    '--config-path=.rustfmt.toml',
    '--',
    '@{{PATHSFILE}}',
]

[[linter]]
code = 'PYRE'
include_patterns = [
    '*.py',
    '**/*.py',
    '**/*.pyi',
]
command = [
    'python3',
    'tools/linter/adapters/pyre_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'pyre-check==0.9.23',
    'click==8.1.0',
]
is_formatter = false
